"""empty message

Revision ID: 34bbbfbbcd16
Revises: 952f4b01f84e
Create Date: 2019-04-27 10:12:21.849121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34bbbfbbcd16'
down_revision = '952f4b01f84e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('database', sa.String(length=40), nullable=True))
    op.add_column('users', sa.Column('hostname', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('port', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'port')
    op.drop_column('users', 'hostname')
    op.drop_column('users', 'database')
    # ### end Alembic commands ###
